
name: myapp

on: push

jobs:

  build-job:

    name: Hello world action

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

      name: Check out code

    - name:echo

      run: echo Hello World
